[versions]
kotlin = "2.1.20"
shadow = "9.0.0-beta15"
serialization = "1.8.1"
kraft = "1.1"
telegram = "26.0.0"
adventure = "4.21.0"
kache = "2.1.1"

[libraries]
serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

kraft = { module = "io.github.xffc.xproject:kraft", version.ref = "kraft" }

telegram = { module = "dev.inmo:tgbotapi", version.ref = "telegram" }

adventure-plain = { module = "net.kyori:adventure-text-serializer-plain", version.ref = "adventure" }

kache = { module = "com.mayakapps.kache:kache", version.ref = "kache" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }