name: build.yml

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build app with artifacts

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          architecture: x64

      - name: Set up gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build artifacts
        run: chmod +x ./gradlew && ./gradlew build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: 'build/libs'
